jcsnorlax97/rentr

- meetingMinutes/Minutes.md
To add the following into both (i) `Minutes.md` in `develop` branch and (ii) Wiki Page.
- Issue #42
> Issue #42: Add Feb 3rd meeting minute into Minutes.md

- Documentation/CORE_FEATURES.md
- README.md
To add project summary & core features into README.md and add a link to the details of the core features.
- Issue #44
> Issue #44: Add project summary & core features into README.md

- Documentation/CORE_FEATURES.md
- README.md
Fix typo & Do small updates for README.md and CORE_FEATURES.md.
> Update README.md and CORE_FEATURES.md

- Documentation/CORE_FEATURES.md
We changed the name of FAQ to QnASection.
> Changed FAQ to Question

- server/controllers/api.js
- Bug: #60 
This PR fix typos for bug issue #60.
N/A
- **Results (After):**
- 30m
Closes #60
> Issue #60: Fix ping API endpoint typo

- server/README.md
- server/api/routes/user.js
- server/controllers/user.js
- server/dao/user.js
- server/services/user.js
- User Stories: #36 
- Dev Tasks: #71 
This PR has implemented a GET route for retrieving a JSON user object based on the given user id. Unit testing would be in another PR.
- [Dependency Injection in Node with awilix](https://github.com/productioncoder/node-dependency-injection)
- **200 (Success)**
- **404 Error (No User with such id)**
- **500 Error (Invalid Id)**
- 1h
N/A
> Issue #71: Implement GET Route for retrieving single user.

- server/README.md
- server/api/index.js
- server/api/routes/listing.js
- server/controllers/listing.js
- server/dao/listing.js
- server/di-setup.js
- server/dto/listing.js
- server/migrations/dropUserTable.sql
- server/migrations/init.sql
- server/services/listing.js
- server/services/listing.test.js
- User Stories: #26 
- Dev Tasks: #67  
This PR implements a POST route for adding new listing & write unit test for it. The route would be `/api/v1/listing`.
The constraint for the input JSON object would be as follows:
- title: string & not null or empty,
- description: string & not null or empty,
- numBedroom: string & not null or empty,
- numBathroom: string & not null or empty, 
This PR also delete the unused `dropTable.sql` in the migration folder.
Note: No integration tests have been done yet.
N/A
- **201 (Success)**
- **400 Error (Empty String in title)**
- **400 Error (Invalid Data Type in numBedroom)**
- 1h 30m
Closes #67
> Issue #67: Implement POST route for adding new listing & Write unit test for it.

- server/api/routes/listing.js
- server/controllers/listing.js
- server/dao/listing.js
- server/services/listing.js
- server/services/listing.test.js
User story: #26 
dev task: #62 
This ticket aims to implement an API endpoint for the front-end to retrieve all existing listings from DB.
Closes #62
> Issue62 task get route for all existing listings

- server/api/routes/user.js
- server/controllers/user.js
- server/dao/user.js
- server/migrations/init.sql
- server/package-lock.json
- server/package.json
- server/services/user.js
**Description**
- Rentr had a register POST route, but needed a login route. 
- Had a controller/service to get user via Id but when logging in we don't know the userId.
- The register route saved the password as plain text, without hashing. 
- Had a VARCHAR(50) limit on the password. 
**Changelog**
- Added POST route for logging in.
- Added a controller/service to get user via email.  
- Added hashhing for registration and login.
- Changed limit on password size from 50 to 500 to account for hash size.
- Login POST method returns JWT Token.
- Added JWT_KEY to .env to use to control user sessions. 
**MISSING**
- middleware does not currently validate JWT tokens
**Registration Works.**
**Registration stores hash which login checks and returns a JWT Token**
> Post route for User Login closes #52

- .gitignore
- frontend/src/actions/CreateListing.js
- frontend/src/components/CreateListing/CreateListingButton.jsx
- frontend/src/pages/HomePage.jsx
- frontend/src/reducers/CreateListing.js
- frontend/src/reducers/index.js
Note that this is going into a feature branch, not develop. 
This should resolve #65 mostly, with the exception of restricting button access to landlords.
This adds a basic button for adding a listing, which causes a basic dialog to appear. The code is somewhat ugly. I'll focus on making things more functional before cleaning it up.
I uninstalled all my extensions and reinstalled using npm install, but my eslint still went nuts on HomePage.jsx. The only non-linter changes I made in that file are lines 24 and 252.
Mostly just a progress update. Didn't really need to make a PR for this.
> #65 Add Add Listing Button and Basic Dialog

- frontend/src/actions/CreateListing.js
- frontend/src/components/CreateListing/CreateListingButton.jsx
- frontend/src/reducers/CreateListing.js
Another PR into a feature branch. Basically another progress update. 
Just the basic UI. This is without much design consideration... styling is yet to be done. Haven't cleaned the code up much yet. I tested the character limits and they seem to work.
> Basic UI of Creating Listing Form

- .gitignore
- frontend/src/actions/CreateListing.js
- frontend/src/components/CreateListing/CreateListingButton.jsx
- frontend/src/pages/HomePage.jsx
- frontend/src/reducers/CreateListing.js
- frontend/src/reducers/index.js
This an almost-full early version of the UI for the create listing dialog. This PR is so that this gets into develop.
Related: #65 #66
One side effect seems to be that the dialog has decreased in width:
> Creating Listing Dialog Basic Form

- server/config/config.js
- server/db/db.js
- server/package.json
- User Stories: N/A
- Dev Tasks: #78
This PR aims to update server in preparation for server deployment into Heroku for front-end to test for functionalities. It also aims to figure out how to deploy the server into Heroku, by deploying the app on this current feature branch. Below is the things that need to be done for the backend deployment.
- https://www.youtube.com/watch?v=CiMHOMeb4Vs (overview)
- https://medium.com/@shalandy/deploy-git-subdirectory-to-heroku-ea05e95fce1f (deploy & build app from sub-directory)
- Deploy sub-directory: git subtree push --prefix server heroku master
- https://coderwall.com/p/ssxp5q/heroku-deployment-without-the-app-being-at-the-repo-root-in-a-subfolder (deploy & build app from sub-directory & feature branch)
- Deploy feature branch: git push heroku `git …
> Issue #78: Update config & db for backend server deployment into Heroku for front-end testing

- server/app.js
- server/dto/user.js
- server/error/api-error-handler.js
- server/migrations/init.sql
- User Stories: N/A
- Dev Tasks: #88
After deploying the backend and the frontend into Heroku, we found that we weren't not able to register new users due to:
1. `Access to XMLHttpRequest at 'https://rentr-dev.herokuapp.com/api/v1/user/registration' from origin 'https://rentr-front-end.herokuapp.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
2. `500 Internal Error`
Based on investigation, the first error is because we are calling back-end server from another domain name, i.e. calling server domain, `https://rentr-dev.herokuapp.com`, from client domain `https://rentr-front-end.herokuapp.com/`. This can be resolved by adding the `cors` middleware in the …
> Issue #88: Fix user registration bugs in deployed environments

- server/.env.template
- server/api/routes/listing.js
- server/api/routes/user.js
- server/controllers/listing.js
- server/controllers/user.js
- server/dao/listing.js
- server/dao/user.js
- server/dto/listing.js
- server/error/api-error.js
- server/middleware/validateLoggedIn.js
- server/migrations/init.sql
- server/services/listing.js
- server/services/listing.test.js
- server/services/user.js
- server/services/user.test.js
- User Stories: N/A
- Dev Tasks: #81 
This PR aims to clean up the back-end project for sprint 2 release, which consists of the following subtasks:
- [PostgreSQL 9.1.24 Documentation - 8.14. Arrays](https://www.postgresql.org/docs/9.1/arrays.html)
- [PostgreSQL 9.1.24 Documentation - 8.6. Boolean Type](https://www.postgresql.org/docs/9.1/datatype-boolean.html)
- [sideway/joi: Empty string not accepted](https://github.com/sideway/joi/issues/251)
- [Joi validation of array](https://stackoverflow.com/questions/42656549/joi-validation-of-array)
- Run DB Script Successfully in Local PostgresDB:
- Smoke Test on API endpoint (1): Ping
- Smoke Test on API endpoint (2): Create New User
- Smoke Test on API endpoint (3): Get Single User via User Id
- Smoke Test on API endpoint (4): Authenticate User …
> Issue #81: Do Final Code Clean Up & Update Listing DB Scheme

- frontend/src/actions/HomePage.js
- frontend/src/components/CreateListing/CreateListingButton.jsx
- frontend/src/components/ImageUpload/ImageUploader.jsx
- frontend/src/components/Listing/listing.jsx
- frontend/src/data/urls.js
- frontend/src/pages/HomePage.jsx
- frontend/src/reducers/HomePage.js
- frontend/src/styles/CreateListing.css
- frontend/src/styles/HomePage.css
- frontend/src/styles/Listing.css
Integrated rest request with login. Removed the mechanism that automatically logs users in when they've just registered.
Integrated post request for post listing.
Integrated get request for listing so that listings could show on the home page.
> Issue #97: Integrate rest services for login, post listing, and fetch listings

- meetingMinutes/Minutes.md
This updates our Documentation/Minutes.md file and updates it so that it is the same as our wiki. Changes after 131 are changes that I've made, and changes above that were made prior to today.
> Update Minutes Documentation

- server/app.js
> Issue #105: Fix "PayloadTooLarge" Bug by adding config parameters to express.json() & express.urlencoded()

- server/README.md
> Issue #102: Update readme in both /server & root-level

- frontend/src/actions/CreateListing.js
- frontend/src/components/CreateListing/CreateListingButton.jsx
- frontend/src/components/ImageUpload/ImageUploader.jsx
- frontend/src/reducers/CreateListing.js
Removed the unecessary code in redux
> Removed the unecessary code

- meetingMinutes/Minutes.md
Included what we did on Friday, the meeting with TA for our sprint 2 evaluation
> Update meeting minute for Week 6

- Documentation/CORE_FEATURES.md
Updates core features and adds links to the epics to it. The feature descriptions are copy/pasted from the epics, which themselves are based on the [Google Doc](https://docs.google.com/document/d/172FQfdT98PY58s-iwek0JeBcySUx4tkakPKJup7XA3E/edit#heading=h.h2yh4ymk48xc)
To view the file, you can check it [here](https://github.com/jcsnorlax97/rentr/blob/Update_Core_Features/Documentation/CORE_FEATURES.md)
> Update core features

- server/api/routes/user.js
- server/controllers/user.js
- server/dao/listing.js
- server/dto/listing.js
- server/migrations/init.sql
- server/services/listing.js
**Changelog**
- Created 2 GET routes for:
-  all listings for a specific user 
- specific listing for a specific user. 
- Front end also receives userid upon successful login.
- Added DROP TABLE at the beginning of init.sql so both tables are dropped and recreated to ensure they rebuild with any updates.
**Screenshots**
1. All listings for a specific user. 
User 1->Listing 1, 2. 
User 2-> Listing 3. 
Both listings for a user are sent. 
2. Requesting a specific user's specific listing. 
The correct Listing is sent. 
When a listing and user don't match, nothing is sent. 
3. UserID is sent upon successful Login
> Issue #149: Get listings for a specific user

- server/api/routes/listing.js
- server/controllers/listing.js
- server/dao/listing.js
- server/dto/listing.js
- server/dto/listingReqQueryString.js
- server/middleware/validateReqQueryString.js
- server/middleware/validateReqQueryString.test.js
- server/migrations/init.sql
- server/services/listing.js
- server/utils/expressMocker.js
- User Stories: #31 #32 
- Dev Tasks: #140
This PR aims to provide filtering feature for GET `/api/v1/listing` request. This PR is responsible for filtering `price`, `num_bathroom`, and `num_bedroom` with use of ranges, for example price range (min_price & max_price).
This PR makes changes on the following files for this filtering functionality:
- Route: `api/routes/listing.js`
- Dto (ListingReqQueryString):
- `middleware/validateReqQueryString.js`
- `dto/listingReqQueryString.js`
- Controller (Listing): `controllers/listing.js`
- Service (Listing): `services/listing.js`
- Dao (Listing): `dao/listing.js`
- Others:
- DB Init Script: `migrations/init.sql`
- Unit Test: `middleware/validateReqQueryString.test.js`
- Helper functions for mocking `req` and `res`: `utils/expressMocker.js`
This PR …
> Issue #140: Filter listing via ranges

- server/dao/listing.js
- server/dto/listingReqQueryString.js
- server/middleware/validateReqQueryString.test.js
- User Stories: #31 #32 
- Dev Tasks: #140
This PR aims to provide filtering feature for GET `/api/v1/listing` request. This PR is responsible for filtering the following boolean values: `is_laundry_available`, `is_pet_allowed`, and `is_parking_available`.
This PR makes changes on the following files for this filtering functionality:
- Dto (ListingReqQueryString):
- `dto/listingReqQueryString.js`
- Dao (Listing): `dao/listing.js`
- Others:
- Unit Test: `middleware/validateReqQueryString.test.js`
N/A
- Listing without filtering - `localhost:5001/api/v1/listing`:
- Listing with filtering via is_laundry_available - `localhost:5001/api/v1/listing?is_laundry_available=true`:
- Listing with filtering via is_pet_allowed - `localhost:5001/api/v1/listing?is_pet_allowed=true`:
- Listing with …
> Issue #141: Filter listing via boolean values

- frontend/src/actions/AdvancedSeach.js
- frontend/src/actions/HomePage.js
- frontend/src/actions/ListingDetail.js
- frontend/src/components/AdvancedSearch.jsx
- frontend/src/components/CreateListing/CreateListingButton.jsx
- frontend/src/components/Listing/listing.jsx
- frontend/src/components/LoginDialogButton.jsx
- frontend/src/data/dropdownData.js
- frontend/src/index.js
- frontend/src/pages/HomePage.jsx
- frontend/src/reducers/AdvancedSearch.js
- frontend/src/reducers/HomePage.js
- frontend/src/reducers/ListingDetail.js
- frontend/src/reducers/index.js
- frontend/src/styles/AdvancedSearch.css
- frontend/src/styles/HomeContent.css
- frontend/src/styles/HomePage.css
- frontend/src/styles/Listing.css
Fully implemented search feature for Rentr
> Implementation of search feature

- server/api/routes/user.js
- server/controllers/user.js
- server/dao/listing.js
- server/services/listing.js
- server/services/listing.test.js
User story: #30  
dev task: #134  
This task aims to implement the delete functionality by creating a DELETE route.
closes #134 
- Successfully deletes:
- After Delete:
- Test passes
> Issue #134: Delete route setup

- frontend/src/components/CreateListing/CreateListingButton.jsx
- frontend/src/components/Listing/listing.jsx
- frontend/src/components/Profile/Profile.jsx
- frontend/src/styles/Listing.css
- Integrated the rest request (get) that returns all listing associated with a specific user.
- Integrated deletion request for a specific user.
- Added warning messages when user want to delete a listing they have
- Added warning messages when the deletion was successful and not successful.
> Integrated rest request for get all listings of a user, also warning messages

- server/README.md
- server/api/routes/listing.js
- server/controllers/chain.js
- server/controllers/comment.js
- server/dao/chain.js
- server/dao/comment.js
- server/di-setup.js
- server/dto/comment.js
- server/migrations/init.sql
- server/services/chain.js
- server/services/chain.test.js
- server/services/comment.js
- server/services/comment.test.js
- User Stories: #119, #120 
- Dev Tasks: #137 
This PR aims to implement two API routes for chain creation and comment creation:
1. `POST /api/v1/listing/:id/chain` (Chain Creation)
2. `POST /api/v1/listing/:id/chain/:chainid/comment` (Comment Creation)
Chain Creation consists of two steps interacting with the database. At first, It will create a new chain into `rentr_chain` table. After that, using the chain id returned from step one, it will initialize the first comment into that chain, by creating a new comment into the `rentr_comment` table. Since this is a Write-Write operation, in order to preserve data integrity, transactions need to be used by executing `BEGIN`, `COMMIT`, and `ROLLBACK`.
Comment Creation would be straight forward. It would simply create a new `comment` and insert …
> Issue #137: Implement POST request for creating chains & comments

- frontend/src/components/Listing/listing.jsx
- frontend/src/components/ListingViewer/ListingViewer.jsx
- frontend/src/pages/HomePage.jsx
- frontend/src/reducers/ListingDetail.js
- frontend/src/styles/HomePage.css
- frontend/src/styles/Listing.css
- frontend/src/styles/ListingView.css
- Updated style for edit panel, which is the right panel
- Now user is able to open and close listing detail panel
- Listing detail panel now is updated when user click on a new listing.
> Updated styles for edit panel and more

- frontend/src/actions/ListingDetail.js
- frontend/src/components/AdvancedSearch.jsx
- frontend/src/components/ImageUpload/ImageUploader.jsx
- frontend/src/components/Listing/listing.jsx
- frontend/src/components/ListingViewer/ListingViewer.jsx
- frontend/src/reducers/ListingDetail.js
- frontend/src/styles/HomePage.css
- frontend/src/styles/Listing.css
- frontend/src/styles/ListingView.css
support editing fields in listings
> Issue #28: Edit posting information is supported

- frontend/src/components/ListingViewer/ListingViewer.jsx
- frontend/src/styles/ListingView.css
This adds my stylesheet to the Mike's QnA branch.
Also made a change to fix zebra striping.
After
Before
> Update QnA stylesheet

- frontend/src/actions/ListingDetail.js
- frontend/src/components/ListingViewer/ListingViewer.jsx
- frontend/src/reducers/ListingDetail.js
- frontend/src/styles/ListingView.css
- user (tenant and landlord) can publicly ask a question about a listing
- user (tenant and landlord) can publicly answer a question
> Added QnA feature

- server/README.md
- server/api/routes/listing.js
- server/api/routes/user.js
- server/controllers/listing.js
- server/controllers/user.js
- server/dao/listing.js
- server/dto/listing.js
- server/error/api-error.js
- server/migrations/init.sql
- server/services/listing.js
- User Stories: #30, #28
- Dev Tasks: #134, #132
- Bug: #156, #157
This PR does:
1. ensure users cannot modify or delete listings owned by other users
2. ensure the `userId` derived from the login is used for listing creation (i.e. the one in `req.body` should be ignored)
3. ensure the associated comments & chains are deleted from the database tables as well, when the listing is deleted, by using `ON DELETE CASCADE`.
4. change listing modification endpoint from `PUT /api/v1/user/:id/listing/:lid` to be `PUT /api/v1/listing/:id`
5. change listing deletion endpoint from `DELETE /api/v1/user/:id/listing/:lid` to be `DELETE /api/v1/listing/:id`
6. add new error type: `403 Unauthorized`
7. update API endpoint documentation: `server/README.md`
Note:
- In POST Listing Creation …
> Issue #134 #132 Bug #156 #157: Modifications & Bug fixing on deleteListing and updateListing 

- frontend/src/components/ListingViewer/ListingViewer.jsx
- frontend/src/components/Profile/Profile.jsx
Updated put and delete with latest api route
> update feature with new api route

- .gitignore
- server/cypress.json
- server/cypress/fixtures/example.json
- server/cypress/integration/Listing_spec.js
- server/cypress/integration/Search_spec.js
- server/cypress/integration/User_account_spec.js
**Description**
- Acceptance testing on the heroku deployment [https://rentr-front-end.herokuapp.com/](https://rentr-front-end.herokuapp.com/)
**Changelog**
-Added Testing for User Account Feature: 
- Login 
- Registration
- Added Testing for Search Feature:
- Simple Single Result Search 
- Simple Multiple Result Search 
- Added Testing for Listing Feature
- Create a new Listing
> Cypress Acceptance Testing

- frontend/package-lock.json
- frontend/package.json
- frontend/src/actions/ListingDetail.js
- frontend/src/components/ListingViewer/ListingViewer.jsx
- frontend/src/reducers/ListingDetail.js
- fixed the issue when adding a new comment, a new question is shown to be added.
- fixed the issue when editing comment of a question, comment area of all questions are showing the same content.
- fixed the issue when exiting a listing, comment, question is not cleared
> QnA bug fix

- server/dao/listing.js
- server/dto/listing.js
- server/migrations/init.sql
- User Stories: #29 
- Dev Tasks: #133 
This PR does:
1. Changes in the INSERT, UPDATE, and SELECT statement for the new field called `is_available` (`dao\listing.js` file).
2. Change in `dto\listing.js` for adding is_available `required()`.
3. Change in the `rentr_listing` table.
Note:
- COALESCE is not used in the SELECT statement (getAllListing) since it will return the 'not available' apartments too.
N/A
- Initial Database:
- Getting all the listings that are available (should return 2 out of 3):
- GetAlllistings work with filters:
- Updating `is_available` works:
-  Getting all the listings that are available (3 out of 3 will return):
- Updating `is_available` false again (works):
- Getting all the listings that are available (2 out of 3 will return):
- Post with availability …
> POST,GET&PUT request works with `is_available` functionality

- frontend/src/Util/DisplayWarning.jsx
- frontend/src/components/ListingViewer/ListingViewer.jsx
- frontend/src/components/ListingViewer/QnA.jsx
- Added notification when update a listing
- Added notification when creating a new question for a listing
- Added notification when creating a new comment for a listing
- Display component is imported and made reusable now
> Notification for update listing and QnA

- frontend/src/actions/ListingDetail.js
- frontend/src/components/CreateListing/CreateListingButton.jsx
- frontend/src/components/ImageUpload/ImageUploader.jsx
- frontend/src/components/Listing/listing.jsx
- frontend/src/components/ListingViewer/ListingViewer.jsx
- frontend/src/components/LoginDialogButton.jsx
- frontend/src/components/Profile/Profile.jsx
- frontend/src/data/dropdownData.js
- frontend/src/reducers/HomePage.js
- frontend/src/reducers/ListingDetail.js
- frontend/src/styles/ListingView.css
Fixed the issue mentioned in issue 181 and 183
> Image upload bug fix

- server/dao/listing.js
- server/dto/listing.js
- server/dto/listingReqQueryString.js
- server/migrations/init.sql
- User Stories: #34  
- Dev Tasks: #124 
This PR does:
1. Changes in the INSERT, UPDATE, and SELECT statement for the new field called `city` (`dao\listing.js` file).
2. Change in `dto\listing.js` for adding city `required()`.
3. Change in `dto\listingReqQueryString.js` for adding city_name.
4. Change in the `rentr_listing` table.
N/A
- Initial Database:
- Update the city name to `Brandon` :
- Getting listings that are located in Brandon (should return 1) :
- Without city name will return a bad request:
- Adding a listing with city name :
- After adding a listing, get the all the listings (will return 2) :
- Closes : #124 , #34
> issue#34-`Search by City` functionality added as the advanced search

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/AdvancedSearch.jsx
- frontend/src/components/CreateListing/CreateListingButton.jsx
- frontend/src/components/Listing/listing.jsx
- frontend/src/components/ListingViewer/ListingViewer.jsx
- frontend/src/components/ListingViewer/QnA.jsx
- frontend/src/components/Profile/Profile.jsx
- frontend/src/data/dropdownData.js
- frontend/src/pages/HomePage.jsx
- frontend/src/reducers/HomePage.js
- frontend/src/styles/AdvancedSearch.css
- frontend/src/styles/Listing.css
- frontend/src/styles/Profile.css
- Added a switch to personal listings, where user can decide whether the listing is available or not
- Added city option when a user is:
- adding a listing
- updating a listing
- searching for a listing
The switch looks like this:
City option for adding a listing, update a listing, and advanced search:
> Issue 43 mike listing cities

- server/config/config.js
- server/migrations/init-demo.sql
- Add new DB environment (`demo`)
- Create new DB init script for presentation demo (`init-demo.sql`)
- Clean up DB init script for Prod environment by adding only one user and one listing (`init.sql`)
> Demo DB Setup

- meetingMinutes/Minutes.md
Meeting minutes have been updated for this sprint (Sprint 4)
> updated meeting minutes
